### PR TITLE
Fix 3.3.0 build

### LINKED ISSUE #39: Plugin breaks Android build
After installing the plugin in your project if you try to build or run an app with `tns run android` the script fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'drawerapp'.
> Could not resolve all dependencies for configuration ':_F0F1F2DebugApkCopy'.
   > Could not find :nativescript-datetimepicker-release:.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
```

We use the plugin in one of our projects and until last week everything was working fine. When we try to do a new build this week this error was thrown. We are using version 1.2.0. Everything works fine on iOS.

**How to reproduce**
Create a new project and add the plugin. Try to run on android.

### PR DESCRIPTION
**Pull request by danielgek**
this fixes #39

### CODE REVIEW

**Comment by AntonioCuevaUrraco** [comment]
@danielgek Nice that you found the cause, but do you know if this is a breaking change on NS 3.3.0?
Are all the other previous NS versions going to break after this change? If you don't know I will try as soon as I have time

**Comment by danielgek** [comment]
@AntonioCuevaUrraco just tested and i think it's backwards compatible(tried with nativescript-cli@3.2.1 and tns-android@3.2.0)

**Comment by danielgek** [comment]
if you prefer i can set peerDependencies

**Comment by AntonioCuevaUrraco** [comment]
@danielgek I tried also in NS 2.5.0 and is working fine there too. So I think it is safe to go. Thank you for the fix.

**Pull request merged**
